source 'http://rubygems.org'

gem 'allure-cucumber'
gem 'capybara', '3.35.3'
gem 'cucumber', '7.0.0'
gem 'money','6.13.8'
gem 'rspec', '3.9.0'
gem 'rspec-retry', '0.6.2'
gem 'selenium-webdriver', '~> 3.5'
gem 'site_prism', '~> 3.7', '>= 3.7.2'
gem 'webdrivers'
