name: Test cucumber

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 5"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        ruby: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Install operating system dependencies
        run: sudo apt-get update -y |
             sudo apt-get install ruby-full
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install operating system dependencies
        run: |
         npm install -g allure-commandline --save-dev
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: |
             gem update --system 3.2.6 |
             gem install cucumber |
             bundle exec cucumber -p default |
             ls -la
      - name: Step 4 - Get allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: 📊 Step 5 - Collect Allure files and generate allure-report folder
        run: |
          allure generate ./build/allure-results -o allure-report/
      - name: 🎁 Step 6 - Publishing Allure artifact to GitHub Actions
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: allure-report
          destination_dir: ${{ matrix.browser}}
