Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@reinaldorossetti 
cucumber
/
cucumber-ruby
Public
243
5.1k
1.1k
Code
Issues
17
Pull requests
4
Actions
Security
Insights
cucumber-ruby/.github/workflows/cucumber-ruby.yml
@aurelien-reeves
aurelien-reeves Move CI to GitHub actions (#1565)
…
Latest commit 3fc5584 on 5 Aug
 History
 6 contributors
@aslakhellesoy@vincent-psarga@romaingweb@mattwynne@cbliard@aurelien-reeves
46 lines (42 sloc)  1.39 KB
  
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Test cucumber

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [2.5,'3.0']
        include:
          - os: ubuntu-latest
            ruby: jruby
        exclude:
          - ruby: 2.5
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        # uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test_chrome_dev_headless
